import type { Café } from "@/types";

// Seed data: Amsterdam specialty coffee spots
export const AMSTERDAM_CAFES: Omit<Café, "id">[] = [
  {
    name: "Lot Sixty One",
    neighborhood: "West",
    address: "Kinkerstraat 112, Amsterdam",
    coordinates: { lat: 52.3638, lng: 4.8668 },
    vibe: "minimalist",
    photo: "/cafes/lot-sixty-one.jpg",
    googleMapsUrl: "https://maps.google.com/?q=Lot+Sixty+One+Amsterdam",
    partnered: false,
    capacity: 3,
  },
  {
    name: "Scandinavian Embassy",
    neighborhood: "De Pijp",
    address: "Sarphatipark 34, Amsterdam",
    coordinates: { lat: 52.3534, lng: 4.8935 },
    vibe: "terrace",
    photo: "/cafes/scandinavian-embassy.jpg",
    googleMapsUrl: "https://maps.google.com/?q=Scandinavian+Embassy+Amsterdam",
    partnered: false,
    capacity: 4,
  },
  {
    name: "Toki",
    neighborhood: "Centrum",
    address: "Binnen Bantammerstraat 15, Amsterdam",
    coordinates: { lat: 52.3748, lng: 4.9003 },
    vibe: "cozy",
    photo: "/cafes/toki.jpg",
    googleMapsUrl: "https://maps.google.com/?q=Toki+Amsterdam",
    partnered: false,
    capacity: 2,
  },
  {
    name: "Coffee Bru",
    neighborhood: "Oost",
    address: "Beukenplein 14, Amsterdam",
    coordinates: { lat: 52.3555, lng: 4.9221 },
    vibe: "terrace",
    photo: "/cafes/coffee-bru.jpg",
    googleMapsUrl: "https://maps.google.com/?q=Coffee+Bru+Amsterdam",
    partnered: false,
    capacity: 3,
  },
  {
    name: "Back to Black",
    neighborhood: "Centrum",
    address: "Weteringstraat 48, Amsterdam",
    coordinates: { lat: 52.3605, lng: 4.8883 },
    vibe: "intimate",
    photo: "/cafes/back-to-black.jpg",
    googleMapsUrl: "https://maps.google.com/?q=Back+to+Black+Amsterdam",
    partnered: false,
    capacity: 2,
  },
  {
    name: "Headfirst Coffee Roasters",
    neighborhood: "West",
    address: "1e Constantijn Huygensstraat 82, Amsterdam",
    coordinates: { lat: 52.3612, lng: 4.8748 },
    vibe: "specialty",
    photo: "/cafes/headfirst.jpg",
    googleMapsUrl: "https://maps.google.com/?q=Headfirst+Coffee+Roasters+Amsterdam",
    partnered: false,
    capacity: 3,
  },
  {
    name: "Sweet Cup",
    neighborhood: "Centrum",
    address: "Damstraat 26, Amsterdam",
    coordinates: { lat: 52.3728, lng: 4.8969 },
    vibe: "cozy",
    photo: "/cafes/sweet-cup.jpg",
    googleMapsUrl: "https://maps.google.com/?q=Sweet+Cup+Amsterdam",
    partnered: false,
    capacity: 2,
  },
  {
    name: "Rum Baba",
    neighborhood: "Oost",
    address: "Czaar Peterstraat 90, Amsterdam",
    coordinates: { lat: 52.3675, lng: 4.9268 },
    vibe: "cozy",
    photo: "/cafes/rum-baba.jpg",
    googleMapsUrl: "https://maps.google.com/?q=Rum+Baba+Amsterdam",
    partnered: false,
    capacity: 3,
  },
  {
    name: "CT Coffee & Coconuts",
    neighborhood: "De Pijp",
    address: "Ceintuurbaan 282-284, Amsterdam",
    coordinates: { lat: 52.3508, lng: 4.8978 },
    vibe: "spacious",
    photo: "/cafes/ct-coffee.jpg",
    googleMapsUrl: "https://maps.google.com/?q=CT+Coffee+Coconuts+Amsterdam",
    partnered: false,
    capacity: 5,
  },
  {
    name: "Monks Coffee Roasters",
    neighborhood: "West",
    address: "Bilderdijkstraat 46, Amsterdam",
    coordinates: { lat: 52.3684, lng: 4.8725 },
    vibe: "specialty",
    photo: "/cafes/monks.jpg",
    googleMapsUrl: "https://maps.google.com/?q=Monks+Coffee+Roasters+Amsterdam",
    partnered: false,
    capacity: 3,
  },
  {
    name: "Two For Joy",
    neighborhood: "Jordaan",
    address: "Haarlemmerdijk 182, Amsterdam",
    coordinates: { lat: 52.3818, lng: 4.8855 },
    vibe: "specialty",
    photo: "/cafes/two-for-joy.jpg",
    googleMapsUrl: "https://maps.google.com/?q=Two+For+Joy+Amsterdam",
    partnered: false,
    capacity: 3,
  },
  {
    name: "Bocca Coffee",
    neighborhood: "Centrum",
    address: "Kerkstraat 96, Amsterdam",
    coordinates: { lat: 52.3635, lng: 4.8876 },
    vibe: "specialty",
    photo: "/cafes/bocca.jpg",
    googleMapsUrl: "https://maps.google.com/?q=Bocca+Coffee+Amsterdam",
    partnered: false,
    capacity: 3,
  },
  {
    name: "de Wasserette",
    neighborhood: "Oost",
    address: "Javaplein 25, Amsterdam",
    coordinates: { lat: 52.3621, lng: 4.9365 },
    vibe: "neighborhood",
    photo: "/cafes/de-wasserette.jpg",
    googleMapsUrl: "https://maps.google.com/?q=de+Wasserette+Amsterdam",
    partnered: false,
    capacity: 4,
  },
  {
    name: "Pluk",
    neighborhood: "Centrum",
    address: "Reestraat 19, Amsterdam",
    coordinates: { lat: 52.3735, lng: 4.8836 },
    vibe: "cozy",
    photo: "/cafes/pluk.jpg",
    googleMapsUrl: "https://maps.google.com/?q=Pluk+Amsterdam",
    partnered: false,
    capacity: 3,
  },
  {
    name: "The Lobby",
    neighborhood: "Centrum",
    address: "Westermarkt 2, Amsterdam",
    coordinates: { lat: 52.3748, lng: 4.8836 },
    vibe: "spacious",
    photo: "/cafes/the-lobby.jpg",
    googleMapsUrl: "https://maps.google.com/?q=The+Lobby+Fizeaustraat+Amsterdam",
    partnered: false,
    capacity: 4,
  },
];
